"""empty message

Revision ID: c52e2bf1e5f1
Revises: 
Create Date: 2024-05-01 15:51:16.537241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c52e2bf1e5f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('registration_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('passed_question', sa.TIMESTAMP(), nullable=True),
    sa.Column('got_2h_autosending', sa.TIMESTAMP(), nullable=True),
    sa.Column('got_24h_autosending', sa.TIMESTAMP(), nullable=True),
    sa.Column('got_48h_autosending', sa.TIMESTAMP(), nullable=True),
    sa.Column('got_72h_autosending', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
